language: java
sudo: required
dist: bionic

jdk:
  - openjdk11

addons:
  apt:
    packages:
      - ant

env:
  - DITA_OT=3.5.4

before_install:
  - zip -r fox.jason.passthrough.doxygen.zip . -x *.zip* *.git/* *temp/* *out/*
  - curl -LO https://github.com/dita-ot/dita-ot/releases/download/$DITA_OT/dita-ot-$DITA_OT.zip
  - unzip -q dita-ot-$DITA_OT.zip
  - chmod +x dita-ot-$DITA_OT/bin/dita

install:
  - dita-ot-$DITA_OT/bin/dita install https://github.com/jason-fox/fox.jason.unit-test/archive/master.zip
  - dita-ot-$DITA_OT/bin/dita install https://github.com/doctales/org.doctales.xmltask/archive/master.zip
  - dita-ot-$DITA_OT/bin/dita install https://github.com/jason-fox/fox.jason.passthrough/archive/master.zip
  - dita-ot-$DITA_OT/bin/dita install fox.jason.passthrough.doxygen.zip

before_script:
  - dita-ot-$DITA_OT/bin/dita --input dita-ot-$DITA_OT/plugins/fox.jason.passthrough.doxygen -f xsl-instrument

script:
  - dita-ot-$DITA_OT/bin/dita --input dita-ot-$DITA_OT/plugins/fox.jason.passthrough.doxygen -f unit-test --output . -v

after_success:
  - cp dita-ot-$DITA_OT/plugins/fox.jason.unit-test/resource/pom.xml pom.xml
  - mvn clean org.eluder.coveralls:coveralls-maven-plugin:report
  - rm -rf dita-ot-$DITA_OT
#  - sonar-scanner  




